version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  test_nets:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: test_nets
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python3 -m unittest tests/test_nets.py

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "test_nets.py" }}

  test_attacks:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: test_attacks
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python3 -m unittest tests/test_attacks.py

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "test_attacks.py" }}
          
  test_one_calls:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: test_one_calls
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python3 -m unittest tests/test_one_calls.py

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "tests/test_one_calls.py" }}

  test_metrics:
    docker:
      - image: circleci/python:3.6.1
    
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: test_metrics
          command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt
              python3 -m unittest tests/test_metrics.py
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "tests/test_metrics.py" }}

  test_trainers:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: test_learners
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python3 -m unittest tests/test_trainers.py

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "tests/test_trainers.py" }}
          
  test_utils:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: test_utils
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python3 -m unittest tests/test_utils.py

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "tests/test_utils.py" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_nets
      - test_attacks
      - test_one_calls
      - test_metrics
      - test_trainers
      - test_utils
